name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install GCC and Make
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Build the Project
        run: make all

      - name: Run Unit Tests
        run: make test

      - name: Clean up
        run: make clean
      
      - name: Install Python Packages and Required Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-tk python3-dev gnome-screenshot xvfb
          cd gtd_frontend
          pip install -r requirements.txt

      - name: Run E2E Test with Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          cd gtd_test
          ./run_e2e.sh
